const videos = [
    {
      id: 1,
      title: 'Face Your Struggles Alone - David Goggins',
      author: 'Inspiring Squad',
      category: 'personal development',
      videoUrl: 'https://www.youtube.com/watch?v=wDC-tFGYT4Y',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'Being Alone Will Make You Full Time SAVAGE ',
      author: 'Inspiring Squad',
      category: 'personal development',
      videoUrl: 'https://www.youtube.com/watch?v=wDC-tFGYT4Y',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 3,
      title: 'David Goggins, True Dog Mentality',
      author: 'Inspiring Squad',
      category: 'personal development',
      videoUrl: 'https://www.youtube.com/watch?v=VORUW-sFvjg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'Ryder Spot - Keep in mind',
      author: 'exocollective',
      category: 'music',
      videoUrl: 'https://www.youtube.com/watch?v=LvISC7BcLuo',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'NightCap - Every Time I Close My Eyes',
      author: 'Epidemic Electronic',
      category: 'music',
      videoUrl: 'https://www.youtube.com/watch?v=DUpVPvvZ3Wg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'Ryder Spot - Splash',
      author: 'Ryder Spot',
      category: 'music',
      videoUrl: 'https://www.youtube.com/watch?v=dp0b66B_ANM',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 7,
      title: 'Yoga for beginners',
      author: 'Yoga with Adriene',
      category: 'fitness',
      videoUrl: 'https://www.youtube.com/watch?v=OQ6NfFIr2jw',  
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'Pilates Flat Stomach in 14 Days',
      author: 'Lilly Sabri',
      category: 'fitness',
      videoUrl: 'https://www.youtube.com/watch?v=G16eeqO2U7g',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'Burn 1000 calories',
      author: 'nobadaddiction',
      category: 'fitness',
      videoUrl: 'https://www.youtube.com/watch?v=yVUcHEOr450',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default videos;